modLoader="javafml"
loaderVersion="[36,)"
license="Mozilla Public License 2.0"

[[mods]]
modId="nwmod"
version="1.1.1"
displayName="NWmod"
credits="Created using mod Auther:MCMjun , Maker MCreator - https://mcreator.net/about"
displayURL="https://mcmjun.github.io/"
logoFile="logo.png"
authors="MCMjun,MCreator"
description='''
A small mod developed by MCMjun.
'''

[[dependencies.nwmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




